"""Chunk-level dense retrieval with a table/figure ablation.

Both arms share one index, one embedding model, one LLM and one prompt. The only
variable is whether chunks parsed from tables and figures are eligible to be
retrieved.

This deliberately bypasses LightRAG's graph modes. Entities were extracted from
*all* chunks, including table and image ones, so their descriptions already carry
multimodal content — masking chunks at query time would not remove it, and the
ablation would be confounded. Chunk-level dense retrieval is the only place the
comparison isolates a single variable.
"""
import json
import pickle

import numpy as np

from paths import VDB_NPY, VDB_PKL, CHUNKS_KV

# MinerU 3.4.4 emits "chart" as a distinct type; the original 272-paper ingest
# (MinerU 2.x, Mar 2026) never produced it. Omitting it would let the text-only
# arm retrieve chart-derived content and silently confound the ablation.
MULTIMODAL_TYPES = ("table", "image", "chart")

# Masking by type alone is not sufficient. Some chunks typed "None" (plain text)
# carry parsed table HTML or a vision-model block verbatim -- 1.2% of otherwise
# unmasked chunks in the original corpus and 3.6% in the newly ingested papers.
# A chunk holding parsed table markup is table-derived content whatever its label,
# so the text-only arm must not see it; otherwise the arm being ablated can still
# read the tables and the comparison measures nothing.
MULTIMODAL_MARKERS = ("<td>", "<table>", "Table Analysis:", "Image Content Analysis:")


def is_multimodal_content(text):
    return any(m in text for m in MULTIMODAL_MARKERS)


class Index:
    def __init__(self, verbose=True):
        if verbose:
            print("loading index...", flush=True)
        # Ingestion writes vdb_chunks.json only; the .npy/.pkl fast-load pair is
        # regenerated by migrate_storage.py. fast_storage falls back to JSON when
        # the .npy is older, but this class reads the binaries directly, so a
        # stale pair would silently benchmark a pre-ingestion index. Refuse instead.
        vdb_json = VDB_NPY.with_suffix(".json")
        if vdb_json.exists() and VDB_NPY.stat().st_mtime < vdb_json.stat().st_mtime:
            raise RuntimeError(
                f"{VDB_NPY.name} is older than {vdb_json.name} — the fast-load index "
                "is stale (papers were ingested after it was built). "
                "Run:  python migrate_storage.py"
            )

        meta = pickle.loads(VDB_PKL.read_bytes())
        self.records = meta["data"]
        self.dim = meta["embedding_dim"]
        self.matrix = np.load(VDB_NPY)
        if self.matrix.shape[0] != len(self.records):
            raise RuntimeError(
                f"index mismatch: {self.matrix.shape[0]} vectors vs "
                f"{len(self.records)} records — rebuild with migrate_storage.py"
            )

        chunks = json.loads(CHUNKS_KV.read_text(encoding="utf-8"))
        self.ids = [r["__id__"] for r in self.records]
        self.files = [r.get("file_path") or "" for r in self.records]
        self.types = np.array(
            [str(chunks.get(i, {}).get("original_type")) for i in self.ids]
        )
        self.contents = [r.get("content") or "" for r in self.records]

        by_type = np.isin(self.types, MULTIMODAL_TYPES)
        by_content = np.array([is_multimodal_content(c) for c in self.contents])
        self.is_multimodal = by_type | by_content

        # Cross-store consistency. The mtime/row-count guards above compare the
        # vector store against itself, which is why they passed while five newly
        # ingested papers sat in the chunk store with no embeddings at all --
        # present in the knowledge base, invisible to retrieval, and scored as
        # retrieval failures. Compare against the chunk store as well.
        self.orphaned = set(chunks) - set(self.ids)
        self.indexed_files = set(self.files)

        if verbose:
            n, pct = int(self.is_multimodal.sum()), self.is_multimodal.mean()
            extra = int((by_content & ~by_type).sum())
            print(f"  {self.matrix.shape[0]} vectors (dim {self.dim}), "
                  f"{n} multimodal ({pct:.1%}) — {int(by_type.sum())} by type "
                  f"+ {extra} by embedded table markup", flush=True)
            if self.orphaned:
                print(f"  WARNING: {len(self.orphaned)} chunks exist in the chunk "
                      f"store but have no vector and cannot be retrieved. "
                      f"Run: python repair_missing_vectors.py", flush=True)

    def assert_retrievable(self, filenames):
        """Refuse to benchmark questions whose source paper has no vectors.

        Scoring such a question records a retrieval failure that says nothing
        about the system under test.
        """
        missing = sorted({f for f in filenames if f and f not in self.indexed_files})
        if missing:
            raise RuntimeError(
                "these source papers have no retrievable chunks, so their "
                "questions cannot be answered by any arm:\n  "
                + "\n  ".join(missing)
                + "\nRun: python repair_missing_vectors.py"
            )

    def search(self, query_vector, top_k=10, exclude_multimodal=False):
        """Cosine top-k. Vectors in the index are stored normalised."""
        q = np.asarray(query_vector, dtype=np.float32)
        q = q / (np.linalg.norm(q) + 1e-12)
        sims = self.matrix @ q
        if exclude_multimodal:
            sims = np.where(self.is_multimodal, -np.inf, sims)
        order = np.argsort(-sims)[:top_k]
        return [
            {
                "chunk_id": self.ids[i],
                "file": self.files[i],
                "type": self.types[i],
                "similarity": round(float(sims[i]), 4),
                "content": self.contents[i],
            }
            for i in order
        ]

    def chunks_for_file(self, filename, types=None):
        out = []
        for i, f in enumerate(self.files):
            if f != filename:
                continue
            if types and self.types[i] not in types:
                continue
            out.append(self.contents[i])
        return out


ARMS = {
    "multimodal": dict(exclude_multimodal=False),
    "text_only": dict(exclude_multimodal=True),
    # Same model, same prompt, no retrieval at all. Comparing only against a
    # commercial model would confound two variables -- retrieval and model
    # identity -- so this arm isolates retrieval while holding the model fixed.
    # It is also the arm that supports the review paper's actual claim, that
    # literature-grounded answering beats ungrounded answering.
    "no_retrieval": dict(context_free=True),
    # A second ungrounded baseline on a different, larger open-weight model.
    # Its role is representativeness: it stands in for "what a researcher would
    # otherwise ask a general-purpose assistant". Being open-weight, anyone can
    # rerun it exactly -- which a commercial chat interface does not allow.
    "gemma3_no_retrieval": dict(context_free=True, model="gemma3:27b"),
}

# Arms that receive no retrieved context. Retrieval metrics are undefined for
# these, and substantiation cannot be computed -- see score.py.
CONTEXT_FREE_ARMS = {"no_retrieval", "gemma3_no_retrieval", "gpt_strict", "gpt_open"}

ANSWER_PROMPT = (
    "Answer the question using ONLY the numbered context below. Report specific "
    "numerical values with their units and the conditions they were measured under. "
    "Cite the context number(s) you used, for example [3]. If the context does not "
    "contain the answer, say so explicitly rather than inferring it.\n\n"
    "--- CONTEXT ---\n{context}\n--- END CONTEXT ---\n\n"
    "Question: {question}\n"
)


# Mirrors ANSWER_PROMPT's instructions as closely as a context-free prompt can,
# so that any difference between arms comes from the presence of retrieved
# evidence rather than from differently worded instructions.
# A context-free arm must NOT receive config.DOMAIN_SYSTEM_PROMPT. That prompt
# asserts "You have access to a comprehensive knowledge base of peer-reviewed
# papers" and instructs the model to "ground your response in the retrieved
# literature; cite specific findings". Handing that to a model with no retrieved
# literature is close to instructing it to invent citations, so any resulting
# fabrication would be an artifact of our own prompt rather than a property of
# ungrounded answering. The retrieval arms keep the domain prompt, because for
# them the claim it makes is true.
NEUTRAL_SYSTEM = (
    "You are an expert scientific assistant specialising in anaerobic digestion, "
    "algae cultivation, and their integration. Use precise scientific terminology "
    "and acknowledge uncertainty or gaps in the literature where relevant."
)

NO_CONTEXT_PROMPT = (
    "Answer the question from your own knowledge. Report specific numerical "
    "values with their units and the conditions they were measured under, and "
    "cite the paper each value comes from. If you do not know a specific value, "
    "say so explicitly rather than estimating or inferring it.\n\n"
    "Question: {question}\n"
)


def build_context(hits, char_limit=1800):
    return "\n\n".join(
        f"[{n}] (source: {h['file']})\n{h['content'][:char_limit]}"
        for n, h in enumerate(hits, 1)
    )
